/* =============================================================================
   ui/icon — ONE icon language: @untitledui/icons.
   -----------------------------------------------------------------------------
   The panel used to draw ninety paths of its own. It draws none now: every
   glyph is Untitled UI's, on one 24-grid at one stroke weight, so an icon in
   the nav, an icon in a button and an icon in a table cell are optically one
   set.

   `Icon name="…"` stays as the panel's own vocabulary — `deal`, `quote`,
   `cash`, `chevr` — because a hundred and fifty files already say those
   words, and a name that means "the deal icon" is more useful to a screen
   than the library's `Briefcase01`. The map below is the whole translation.
   A view may also import a glyph straight from `@untitledui/icons` and hand
   it to a component that takes `icon={…}` — both routes reach the same set.

   An unknown name renders the document glyph rather than nothing: a missing
   icon should be a wrong drawing somebody notices, never an invisible gap in
   a toolbar that silently changes the spacing of everything beside it.

   SIZES. xs 12 · sm 16 · (md) 20 · lg 24 · xl 32. Stroke follows Untitled
   UI's convention: 2px at 20, tightened to 2.25 at 16 and below so a small
   glyph does not go thin.
   ========================================================================== */
import type { FC, SVGProps } from "react";
import {
    Activity,
    AlertTriangle,
    Announcement01,
    Archive,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    BankNote01,
    BarChart01,
    Bell01,
    Briefcase01,
    Building07,
    Calendar,
    Check,
    CheckCircle,
    ChevronDown,
    Columns03,
    CurrencyRupee,
    FileAttachment02,
    Globe01,
    Hash01,
    Hourglass01,
    LayoutAlt01,
    MessageTextSquare02,
    Monitor01,
    Moon01,
    Repeat01,
    Rows01,
    Sun,
    Table,
    XCircle,
    Zap,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Clock,
    ClockRewind,
    Coins01,
    Copy01,
    CreditCard01,
    DotsHorizontal,
    DotsVertical,
    Download01,
    Edit01,
    Expand01,
    Eye,
    EyeOff,
    File02,
    File04,
    File06,
    FileCheck02,
    FilterLines,
    Flag01,
    FlipBackward,
    Folder,
    GitBranch01,
    Grid01,
    HelpCircle,
    Home02,
    Image01,
    Inbox01,
    InfoCircle,
    LayersThree01,
    LifeBuoy01,
    Link01,
    List,
    Lock01,
    LockUnlocked01,
    LogOut01,
    Mail01,
    MarkerPin01,
    Menu01,
    MessageCircle01,
    Minus,
    PauseCircle,
    Percent01,
    Phone,
    PieChart01,
    Play,
    Plus,
    Printer,
    Receipt,
    RefreshCw01,
    Save01,
    SearchLg,
    Settings01,
    Share04,
    Shield01,
    Sliders01,
    Square,
    Star01,
    Stars01,
    StickerSquare,
    SwitchVertical01,
    Tag01,
    Target01,
    Trash01,
    TrendUp01,
    Upload01,
    User01,
    Users01,
    Users02,
    Wallet02,
    X,
} from "@untitledui/icons";
import { cx } from "@/utils/cx";

export type IconComponent = FC<SVGProps<SVGSVGElement> & { className?: string; strokeWidth?: number | string }>;

/** The panel's icon vocabulary → the library's glyph. One line per name. */
export const ICONS: Record<string, IconComponent> = {
    home: Home02,
    deal: Briefcase01,
    quote: File06,
    invoice: FileCheck02,
    chart: BarChart01,
    route: GitBranch01,
    users: Users01,
    store: Building07,
    tag: Tag01,
    cash: BankNote01,
    out: ArrowDown,
    recon: SwitchVertical01,
    refund: FlipBackward,
    coin: Coins01,
    mega: Announcement01,
    doc: File02,
    flag: Flag01,
    life: LifeBuoy01,
    team: Users02,
    shield: Shield01,
    history: ClockRewind,
    search: SearchLg,
    bell: Bell01,
    chev: ChevronDown,
    chevr: ChevronRight,
    chevl: ChevronLeft,
    chevu: ChevronUp,
    alert: AlertTriangle,
    clock: Clock,
    calendar: Calendar,
    lock: Lock01,
    unlock: LockUnlocked01,
    arrow: ArrowRight,
    ext: Share04,
    menu: Menu01,
    x: X,
    plus: Plus,
    filter: FilterLines,
    download: Download01,
    check: Check,
    dots: DotsVertical,
    dotsh: DotsHorizontal,
    inbox: Inbox01,
    sparkle: Stars01,
    logout: LogOut01,
    user: User01,
    building: Building07,
    link: Link01,
    star: Star01,
    eye: Eye,
    eyeoff: EyeOff,
    minus: Minus,
    trash: Trash01,
    edit: Edit01,
    copy: Copy01,
    info: InfoCircle,
    help: HelpCircle,
    settings: Settings01,
    sliders: Sliders01,
    upload: Upload01,
    refresh: RefreshCw01,
    mail: Mail01,
    phone: Phone,
    chat: MessageCircle01,
    pin: MarkerPin01,
    target: Target01,
    layers: LayersThree01,
    folder: Folder,
    image: Image01,
    play: Play,
    pause: PauseCircle,
    stop: Square,
    print: Printer,
    share: Share04,
    archive: Archive,
    undo: FlipBackward,
    up: ArrowUp,
    down: ArrowDown,
    left: ArrowLeft,
    expand: Expand01,
    grid: Grid01,
    list: List,
    sort: SwitchVertical01,
    save: Save01,
    wallet: Wallet02,
    file: File04,
    filecheck: FileCheck02,
    percent: Percent01,
    trend: TrendUp01,
    pie: PieChart01,
    activity: Activity,
    note: StickerSquare,
    receipt: Receipt,
    card: CreditCard01,
    sun: Sun,
    moon: Moon01,
    monitor: Monitor01,
    columns: Columns03,
    kanban: LayoutAlt01,
    timeline: Rows01,
    table: Table,
    bolt: Zap,
    globe: Globe01,
    repeat: Repeat01,
    hourglass: Hourglass01,
    checkcircle: CheckCircle,
    xcircle: XCircle,
    attach: FileAttachment02,
    hash: Hash01,
    rupee: CurrencyRupee,
    message: MessageTextSquare02,
};

export type IconName = keyof typeof ICONS;

const SIZES = {
    xs: "size-3 stroke-[2.5px]",
    sm: "size-4 stroke-[2.25px]",
    md: "size-5",
    lg: "size-6",
    xl: "size-8 stroke-[1.75px]",
} as const;

export function Icon({
    name,
    size = "md",
    className,
    ...rest
}: {
    name: string;
    size?: keyof typeof SIZES;
    className?: string;
} & Omit<SVGProps<SVGSVGElement>, "name" | "className">) {
    const Glyph = ICONS[name] || ICONS.doc;
    return <Glyph aria-hidden="true" data-icon className={cx("shrink-0", SIZES[size], className)} {...rest} />;
}

/** The glyph itself, for components that take `icon={Component}`. */
export const iconOf = (name: string): IconComponent => ICONS[name] || ICONS.doc;
