/* =============================================================================
   Business Enquiries — Module 4 · the route component.
   -----------------------------------------------------------------------------
   Renamed from "Client Enquiry Management". The record is a BUSINESS ENQUIRY:
   a customer opportunity, generated by an Interior bazzar funnel page or the
   portal enquiry form, qualified once, matched by rules the module can explain,
   and routed to exactly one subscribed business.

   `#/business-enquiries`          the queue
   `#/business-enquiries/:id`      one enquiry, its suggestions, its history
   `?tab=match|assignment|history` which face of the record
   `?new=1`                        the Add-an-enquiry dialog, as a link

   The detail is a PAGE, not a drawer. Deals and Plans open a record over the
   list they were reading it from, which is right when the record is a summary
   you glance at. This one is a decision surface: requirement, qualification and
   four ranked businesses with their reasons have to be on screen together, and
   a drawer over a table cannot carry that without one of the two being a
   scroll away.
   ============================================================================= */
import { useCallback, useEffect, useMemo, useRef } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { hashToPath, usePageChrome } from "../../shell/AdminShell";
import { useShell } from "../../shell/ShellContext";
import { Button, EmptyState, PaneLoading, qs, TbTitle } from "../../ui";
import List, { enquiryHash, listHash, merge, omit } from "./List";
import Detail from "./Detail";
import NewEnquiryModal from "./NewEnquiry";
import {
  bootBusinessEnquiries, queryFromParams, useBoot, useEnquiryPage, useIntakeCounts,
} from "./store";
import type { Params } from "./store";

/* The vocabulary, the matching rules and the business directory come from the
   API and every screen below reads them synchronously, so the module waits for
   them here rather than threading a loading state through twelve files.

   A failure is PRINTED, not papered over. There is no bundled copy of this data
   any more: if this block is on screen the backend is not answering, and that is
   exactly what it should look like. */
function BootGate() {
  const boot = useBoot();
  if (boot.error) {
    return (
      <EmptyState
        icon="alert"
        title="Business Enquiries could not load"
        body={
          <>
            The panel reads its vocabulary, matching rules and business directory from{" "}
            <span className="font-mono">/api/v1/admin/business-enquiries/</span>. That request failed,
            so there is nothing to show — this module keeps no local copy of them on purpose.
            <span className="mt-2 block font-medium text-secondary">{boot.error}</span>
          </>
        }
        action={<Button color="primary" ico="refresh" onClick={() => void bootBusinessEnquiries(true)}>Retry</Button>}
      />
    );
  }
  if (!boot.ready) return <PaneLoading label="Loading the enquiry vocabulary…" />;
  return <BusinessEnquiriesRoute />;
}

export default BootGate;

function BusinessEnquiriesRoute() {
  const raw = useParams().id;
  const id = raw ? decodeURIComponent(raw) : null;
  const [sp] = useSearchParams();
  const navigate = useNavigate();
  const { toast, modal, closeLayer } = useShell();

  const p = useMemo(() => {
    const o: Params = {};
    sp.forEach((v, k) => { if (v) o[k] = v; });
    return o;
  }, [sp]);

  /* `new` is a DIALOG SWITCH, not a filter: it must not reach the query, the
     chips row or the "how many filters are on" count. Everything below reads
     `lp` — the URL minus that one key — and only the dialog itself reads `p`. */
  const lp = useMemo(() => omit(p, ["new"]), [p]);

  /* THE PAGE, from the server, keyed on the filters in the URL. `page` is part
     of the URL like every other filter, so a link to page 3 of the breached
     queue is a link somebody can send. */
  const pageNo = Math.max(1, Number(lp.page) || 1);
  const query = useMemo(() => queryFromParams(omit(lp, ["tab", "page"]), pageNo),
    [lp, pageNo]);
  const page = useEnquiryPage(query);
  const all = page.rows;

  /* ------------------------------------------------------------ topbar ---
     INTAKE, not lifecycle. The strip on the page already counts every state and
     counts them better — repeating two of them in the topbar said nothing the
     page was not already saying louder. What the topbar can say that the strip
     cannot is how much is COMING IN, which is the number you want before you
     look at the queue at all.

     Counted by the SERVER over the whole queue, not over this page — the topbar
     numbers would otherwise never exceed the page size, and they are unfiltered
     on purpose: how much is coming in must not change meaning because somebody
     narrowed the list. */
  const { today, week } = useIntakeCounts();
  const crumbs = useMemo(() => (
    <>
      <TbTitle label="Business Enquiries" to="#/business-enquiries" />
      <span className="ml-3 hidden items-center gap-3 sm:flex">
        {/* Label first, then the figure. "0 today" reads as a sentence fragment
            you have to finish; "today 0" reads as a labelled value, which is
            what it is. */}
        <IntakeStat k="today" v={today} />
        <IntakeStat k="last 7 days" v={week} />
      </span>
    </>
    /* usePageChrome republishes once per LOCATION, not per render, so this
       memo only has to be right for the counts it prints. */
  ), [today, week]);

  /* Where "up" is. From a record, the list it was opened from — filters and
     all, so Back is a return and not a reset. */
  /* Keyed on the counts: they come from the server after the first render, and
     without the key the topbar would keep the zeros it mounted with. */
  usePageChrome({ crumbs, right: null, parent: id ? listHash(omit(lp, ["tab"])) : null },
    `${today}/${week}`);

  /* ----------------------------------------------------------- filters ---
     Same debounce Deals uses for search: typing must not push a history entry
     per keystroke. Every other control commits immediately. */
  const timer = useRef<number | undefined>(undefined);
  /* A filter change is not a place you navigated TO — it is the same place,
     narrowed. Pushing one history entry per filter (and one per search pause)
     made Back walk backwards through filter states instead of leaving the list,
     which is the only thing anyone presses it for here. */
  const goFilter = useCallback((hash: string) => {
    navigate(hashToPath(hash), { replace: true });
  }, [navigate]);
  /* EVERY FILTER CHANGE GOES BACK TO PAGE 1. Page 7 of the unfiltered queue is
     usually past the end of a filtered one, and the empty table that follows
     reads as "nothing matches" when the answer is "not on page 7". */
  const onFilter = useCallback((name: string, value: string) => {
    goFilter(listHash(merge(omit(lp, ["tab", "page"]), { [name]: value })));
  }, [lp, goFilter]);
  const onSearch = useCallback((name: string, value: string) => {
    window.clearTimeout(timer.current);
    timer.current = window.setTimeout(
      () => goFilter(listHash(merge(omit(lp, ["tab", "page"]), { [name]: value }))), 220);
  }, [lp, goFilter]);
  const onUnfilter = useCallback((k: string) => {
    /* A key may carry its dependants, joined by "+": removing the received
       range has to remove the from/to it was made of, or the next range picked
       silently inherits the old custom bounds. */
    const keys = k === "*" ? [] : k.split("+");
    goFilter(k === "*" ? listHash({}) : listHash(omit(lp, keys.concat(["tab"]))));
  }, [lp, goFilter]);
  useEffect(() => () => window.clearTimeout(timer.current), []);

  /* -------------------------------------------------------- add an enquiry ---
     THE DIALOG IS A URL, so it can be linked, reloaded into and photographed —
     `?new=1`, the same switch Quotations and Invoices use for their own create
     step. Pressing the button opens it AND writes the param; arriving on a link
     that already carries the param opens it on mount. Both paths run the one
     `openNew` below, so there is no second copy of what the dialog is given. */
  const closeNew = useCallback(() => {
    closeLayer();
    navigate(hashToPath(listHash(lp)), { replace: true });
  }, [closeLayer, navigate, lp]);

  /* Straight to the new record, not back to the list: whoever just typed it is
     still on the call, and the next thing they need is the contact log they are
     about to write into. */
  const openNew = useCallback(() => {
    modal(
      <NewEnquiryModal
        onClose={closeNew}
        onDone={(newId, msg) => {
          closeLayer();
          toast(msg);
          navigate(hashToPath(enquiryHash(newId, {})));
        }} />,
      "lg");
    if (p.new !== "1") {
      navigate(hashToPath(listHash(merge(lp, { new: "1" }))), { replace: true });
    }
  }, [modal, closeNew, closeLayer, toast, navigate, p.new, lp]);

  /* Once, on arrival. A later change to the param is not watched on purpose:
     the button is the only thing that sets it while this page is mounted, and
     it opens the dialog itself. */
  const booted = useRef(false);
  useEffect(() => {
    if (booted.current) return;
    booted.current = true;
    if (p.new === "1" && !id) openNew();
  }, [p.new, id, openNew]);

  /* THE QUEUE, AS THE RECORD SEES IT — the page the operator was looking at,
     in the order they were looking at it, so "next" means next in what they
     were reading rather than next by id. A record opened from a link and not on
     that page still renders: Detail reads it by id, and it simply has no
     position and no neighbours, which is the truth about it.
     ponytail: prev/next stop at the page edge rather than loading the next
     page. Stepping off the end of fifty rows is rare; a silent extra fetch
     every time somebody holds the key down is not. */
  const queue = all;
  const at = id ? queue.findIndex((x) => x.enquiryId === id) : -1;
  const hashOf = (n: number) =>
    queue[n] ? enquiryHash(queue[n].enquiryId, omit(lp, ["tab"])) : null;
  const offset = (page.pageNo - 1) * page.pageSize;

  if (id) {
    return (
      <Detail id={id} listHash={listHash(omit(lp, ["tab"]))}
        prev={at > 0 ? hashOf(at - 1) : null}
        next={at >= 0 && at < queue.length - 1 ? hashOf(at + 1) : null}
        /* No position when the record is not in the current filter — a record
           opened from a link, or one whose status just changed under a filter
           it no longer matches. Showing "0 of 9" there would be a lie. */
        pos={at >= 0 ? { i: offset + at + 1, of: page.total } : null} />
    );
  }

  return (
    <List all={all} page={page} p={lp} sel={null}
      onPage={(n) => goFilter(listHash(merge(omit(lp, ["tab"]), { page: String(n) })))}
      onFilter={onFilter} onSearch={onSearch} onUnfilter={onUnfilter} toast={toast}
      onCreate={openNew} />
  );
}

/* One intake figure in the topbar. Small enough that a shared part would be a
   part with one caller, so it is drawn here from the utilities. */
function IntakeStat({ k, v }: { k: string; v: number }) {
  return (
    <span className="inline-flex items-baseline gap-1.5">
      <span className="label-mono">{k}</span>
      <span className="text-sm font-semibold text-primary tnum">{Number(v) || 0}</span>
    </span>
  );
}

/* Re-exported so the shell's command palette and any cross-module link build
   the same addresses this module does, rather than hand-writing hashes. */
export { enquiryHash, listHash };
export const enquiriesRoute = (p: Params = {}) => "#/business-enquiries" + qs(p as Record<string, string>);
