/* =============================================================================
   Business Enquiries — Module 4 · the route component.
   -----------------------------------------------------------------------------
   Renamed from "Client Enquiry Management". The record is a BUSINESS ENQUIRY:
   a customer opportunity, generated by an Interior bazzar funnel page or the
   portal enquiry form, qualified once, matched by rules the module can explain,
   and routed to exactly one subscribed business.

   `#/business-enquiries`          the queue
   `#/business-enquiries/:id`      one enquiry, its suggestions, its history
   `?tab=match|assignment|history` which face of the record

   NO API YET. Everything is read from `src/content/business-enquiries/*.json`
   and every write lands in memory for this tab only — see store.ts for what the
   simulation does and does not honour, and `src/proto/v-2.2.0.0/` for the
   endpoint work-list this stands in for.

   The detail is a PAGE, not a drawer. Deals and Plans open a record over the
   list they were reading it from, which is right when the record is a summary
   you glance at. This one is a decision surface: requirement, qualification and
   four ranked businesses with their reasons have to be on screen together, and
   a drawer over a table cannot carry that without one of the two being a
   scroll away.
   ============================================================================= */
import { useCallback, useEffect, useMemo, useRef } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { hashToPath, usePageChrome } from "../../shell/AdminShell";
import { useShell } from "../../shell/ShellContext";
import { qs } from "../../ui";
import List, { enquiryHash, listHash, merge, omit } from "./List";
import Detail from "./Detail";
import NewEnquiryModal from "./NewEnquiry";
import { countsOf, filterEnquiries, sortEnquiries, useEnquiries } from "./store";
import type { Params } from "./store";
import "./enquiries.css";

export default function BusinessEnquiries() {
  const raw = useParams().id;
  const id = raw ? decodeURIComponent(raw) : null;
  const [sp] = useSearchParams();
  const navigate = useNavigate();
  const { toast, modal, closeLayer } = useShell();
  const all = useEnquiries();

  const p = useMemo(() => {
    const o: Params = {};
    sp.forEach((v, k) => { if (v) o[k] = v; });
    return o;
  }, [sp]);

  /* ------------------------------------------------------------ topbar ---
     The counts sit beside the title rather than only in the strip, because the
     one number an operator wants without scrolling is how many are waiting on
     a decision — and on the detail page the strip is not on screen at all. */
  const m = countsOf(all);
  const crumbs = useMemo(() => (
    <>
      <span className="tb-title">Business Enquiries</span>
      <span className="tb-stats">
        <span className="tb-stat ro"><span className="v tnum">{m.ready}</span><span className="k">ready</span></span>
        <span className="tb-stat ro"><span className="v tnum">{m.live}</span><span className="k">live</span></span>
        {m.breached
          ? <span className="tb-stat ro bad"><span className="v tnum">{m.breached}</span><span className="k">breached</span></span>
          : null}
      </span>
    </>
    /* usePageChrome republishes once per LOCATION, not per render, so this
       memo only has to be right for the counts it prints. */
  ), [m.ready, m.live, m.breached]);

  /* Where "up" is. From a record, the list it was opened from — filters and
     all, so Back is a return and not a reset. */
  usePageChrome({ crumbs, right: null, parent: id ? listHash(omit(p, ["tab"])) : null });

  /* ----------------------------------------------------------- filters ---
     Same debounce Deals uses for search: typing must not push a history entry
     per keystroke. Every other control commits immediately. */
  const timer = useRef<number | undefined>(undefined);
  /* A filter change is not a place you navigated TO — it is the same place,
     narrowed. Pushing one history entry per filter (and one per search pause)
     made Back walk backwards through filter states instead of leaving the list,
     which is the only thing anyone presses it for here. */
  const goFilter = useCallback((hash: string) => {
    navigate(hashToPath(hash), { replace: true });
  }, [navigate]);
  const onFilter = useCallback((name: string, value: string) => {
    goFilter(listHash(merge(omit(p, ["tab"]), { [name]: value })));
  }, [p, goFilter]);
  const onSearch = useCallback((name: string, value: string) => {
    window.clearTimeout(timer.current);
    timer.current = window.setTimeout(
      () => goFilter(listHash(merge(omit(p, ["tab"]), { [name]: value }))), 220);
  }, [p, goFilter]);
  const onUnfilter = useCallback((k: string) => {
    /* A key may carry its dependants, joined by "+": removing the received
       range has to remove the from/to it was made of, or the next range picked
       silently inherits the old custom bounds. */
    const keys = k === "*" ? [] : k.split("+");
    goFilter(k === "*" ? listHash({}) : listHash(omit(p, keys.concat(["tab"]))));
  }, [p, goFilter]);
  useEffect(() => () => window.clearTimeout(timer.current), []);

  /* A record that no longer matches the filters it was opened under is still a
     real record — the detail reads the store directly and never the filtered
     page, so marking an enquiry invalid while filtered to Ready does not blank
     the screen you are standing on. */
  /* THE QUEUE, AS THE RECORD SEES IT. Computed here rather than in Detail
     because it must be the SAME filtered and sorted list the operator was
     looking at — stepping to "next" has to mean next in what they were
     reading, not next by id. */
  const queue = sortEnquiries(filterEnquiries(all, omit(p, ["tab"])), p.sort);
  const at = id ? queue.findIndex((x) => x.enquiryId === id) : -1;
  const hashOf = (n: number) =>
    queue[n] ? enquiryHash(queue[n].enquiryId, omit(p, ["tab"])) : null;

  if (id) {
    return (
      <Detail id={id} listHash={listHash(omit(p, ["tab"]))}
        prev={at > 0 ? hashOf(at - 1) : null}
        next={at >= 0 && at < queue.length - 1 ? hashOf(at + 1) : null}
        /* No position when the record is not in the current filter — a record
           opened from a link, or one whose status just changed under a filter
           it no longer matches. Showing "0 of 9" there would be a lie. */
        pos={at >= 0 ? { i: at + 1, of: queue.length } : null} />
    );
  }

  /* Straight to the new record, not back to the list: whoever just typed it is
     still on the call, and the next thing they need is the contact log they are
     about to write into. */
  const onCreate = () => modal(
    <NewEnquiryModal
      onClose={closeLayer}
      onDone={(newId, msg) => {
        closeLayer();
        toast(msg);
        navigate(hashToPath(enquiryHash(newId, {})));
      }} />,
    "wide"
  );

  return (
    <List all={all} p={p} sel={null}
      onFilter={onFilter} onSearch={onSearch} onUnfilter={onUnfilter} toast={toast}
      onCreate={onCreate} />
  );
}

/* Re-exported so the shell's command palette and any cross-module link build
   the same addresses this module does, rather than hand-writing hashes. */
export { enquiryHash, listHash };
export const enquiriesRoute = (p: Params = {}) => "#/business-enquiries" + qs(p as Record<string, string>);
